Tarea3-4/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  resources :drivers
  resources :cars
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :prueba

  end
  

Tarea3-4/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Tarea3-4/app/models/car.rb
class Car < ApplicationRecord
end

Tarea3-4/app/models/driver.rb
class Driver < ApplicationRecord
end

Tarea3-4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Tarea3-4/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]

  # GET /cars or /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:model, :brand, :driver_id, :code)
    end
end

Tarea3-4/app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: %i[ show edit update destroy ]

  # GET /drivers or /drivers.json
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1 or /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers or /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: "Driver was successfully created." }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1 or /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: "Driver was successfully updated." }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1 or /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: "Driver was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def driver_params
      params.require(:driver).permit(:name, :code)
    end
end

Tarea3-4/app/controllers/terms_controller.rb
class TermsController < ApplicationController
    def index
    end
end

Tarea3-4/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Tarea3-4/app/helpers/application_helper.rb
module ApplicationHelper
end

Tarea3-4/app/helpers/cars_helper.rb
module CarsHelper
end

Tarea3-4/app/helpers/drivers_helper.rb
module DriversHelper
end

Tarea3-4/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Tarea3-4/app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :model %>
    <%= form.number_field :model %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :driver_id %>
    <%= form.number_field :driver_id %>
  </div>

  <div class="field">
    <%= form.label :codeee %>
    <%= form.text_field :code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Tarea3-4/app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

Tarea3-4/app/views/cars/index.html.erb
<link rel="stylesheet" href="Tarea4\app\assets\stylesheets\cars.scss">
<p id="notice"><%= notice %></p>
<body class=bcars>
<h1 class="main_title">Cars</h1>
<h1 class="sub_title">Carlos Reyes</h1>
<table>
  <thead>
    <tr>
      <th class="encabezado">Model</th>
      <th class="encabezado">Brand</th>
      <th class="encabezado">Driver</th>
      <th class="encabezado">Code</th>
      <th class="encabezado">Actions</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td class="registro"><%= car.model %></td>
        <td class="registro"><%= car.brand %></td>
        <td class="registro"><%= car.driver_id %></td>
        <td class="registro"><%= car.code %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Car', new_car_path %>
</body>

Tarea3-4/app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

Tarea3-4/app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @car.brand %>
</p>

<p>
  <strong>Driver:</strong>
  <%= @car.driver_id %>
</p>

<p>
  <strong>Code:</strong>
  <%= @car.code %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

Tarea3-4/app/views/drivers/_form.html.erb
<%= form_with(model: driver) do |form| %>
  <% if driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
        <% driver.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Tarea3-4/app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

Tarea3-4/app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drivers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Actions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= driver.name %></td>
        <td><%= driver.code %></td>
        <td><%= link_to 'Show', driver %></td>
        <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
        <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Driver', new_driver_path %>

Tarea3-4/app/views/drivers/new.html.erb
<h1>New Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Back', drivers_path %>

Tarea3-4/app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @driver.name %>
  <%= @driver.code %>
</p>

<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>

Tarea3-4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tarea3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Tarea3-4/app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <title>Tarea #4</title>
</head>
<nav class="navegador">
    <ul>
        <li><%= link_to 'Carros', cars_path%></li>
        <li><%= link_to 'Conductures', drivers_path%></li>
    </ul> 
    <!--<%= link_to 'Google', "https://www.google.com/"%>-->
</nav>
<body>
    <div class="contenedor">
        <div class="subcontenedor">
            <h1 class="titulo_principal">¿Qué he aprendido?</h1>
            <p>He aprendido cómo crear proyectos de Ruby, generar scaffolds y apartir de esos generar migraciones. Estoy de igual forma, aprendiendo la estructura básica de SASS y cómo implementar Bulma al proyecto. Me gustaría seguir aprendiendo un poco de todo e ir afinando mis conocimientos sobre todas las herramientas que se usan para realizar un proyecto en la empresa Lomax Technologies.</p>
            <%= image_tag("portada.png", :alt => "Foto de perfil") %>
            <!--<img src="Tarea4\app\assets\images\FotoPerfil.jpg" alt="" width="50" height="50">-->
            <button class="button is-light is-info"><%= link_to 'Conoce más sobre mí', "https://carlosreyes96.github.io/CarlosReyes-Portafolio/"%></button>
        </div>
    </div>
    <footer class="piePagina">  
        <p>@Copyright Lomax Technologies 2021 - All Right Reserved. <p>  
    </footer> 
</body> 
</html>